### ISSUE TITLE
Fix getGriefingCollateral tests

### ISSUE THREAD

**Issue by bvotteler** [interlay/interbtc-api#516]
Adding multi-collateral vaults to the tests have broken “should getGriefingCollateral” tests for both issue and replace.

It seems the running oracle is interfering with the artificially set exchange rate.

To fix: Look at oracle tests where we use mocks to fix the exchange rate for the scope of the test and re-use that pattern.

Additional note: Look at [Greg’s comment here](https://github.com/interlay/interbtc-api/pull/415#discussion_r890011389), and check if these tests can be reworked completely

**Comment by gregdhill** [comment]
Closed by https://github.com/interlay/interbtc-api/pull/578
