### ISSUE TITLE
Investigate feasibility of full extrinsic builder

### ISSUE THREAD

**Issue by bvotteler** [interlay/interbtc-api#518]
The lib has had methods added to construct many extrinsics.
Currently, those are called as methods on various API instances, gathered in an array/vector by the consumer, to then be wrapped in a batch call.

Investigate how much effort it takes to change that into a fully fledged builder. Particularly also with regards to having an option to ensure multiple events have been sent (and maybe even in order).

For more info, see this comment on the original pull request: https://github.com/interlay/interbtc-api/pull/470#pullrequestreview-1107312479

**Comment by bvotteler** [comment]
Things to take into consideration:
- The various components have instances to utilize for calculations (eg. Asset Registry to resolve currencies), check if we can easily pass the InterBtcAPI and TransactionAPI instances into a builder constructor to make them available.
- Check if the events emit in the same order as the parachain executes the batched extrinsics. If so, check what it takes to programmatically get the actually emitted events in order.
- Take hidden complexities like runtime exceptions that only arise due to builder state into consideration.

**Comment by nud3l** [comment]
Deprecated in favour of #592
