### ISSUE TITLE
Handle errors in `docker-parachain-stop` yarn script

### ISSUE THREAD

**Issue by daniel-savu** [interlay/interbtc-api#580]
**Is your feature request related to a problem? Please describe.**
`yarn docker-parachain-stop` will throw an error that is hard to debug if `yarn docker-parachain-start` has not been run before. 

**Describe the solution you'd like**
Create a custom script, similar to [the one for starting the nodes](https://github.com/interlay/interbtc-api/blob/67ec5048eccc1fff168226b9ee3858902f9787a5/package.json#L48), that checks for this error condition (`No such file or directory: './local-setup/docker-compose.yml'`) and prints a helpful error message ("run `yarn docker-parachain-stop` first").

Also applies to the https://github.com/interlay/bots repo.

**Comment by gregdhill** [comment]
I think this is no longer relevant (https://github.com/interlay/interbtc-api/pull/578), @daniel-savu please re-open if you disagree.
