### ISSUE TITLE
Markets is undefined in interlay-api

### ISSUE THREAD

**Issue by Chanakya888** [interlay/interbtc-api#624]
**Describe the bug**
Vaults page on frontend is throwing a type error: Cannot read properties of undefined (reading 'markets') at ../node_modules/@interlay/interbtc-api/build/src/parachain/loans.js

**To Reproduce**
1. Go to '/dashboard/vaults' in the interbtc-ui
2. Wait for a couple of seconds to see the error

**Expected behavior**
Vaults table is visible with respective vaults data

**Screenshots**
<img width="750" alt="image" src="https://user-images.githubusercontent.com/26459789/230592275-f7a31e41-be66-4bc1-9041-d859956b3c04.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/26459789/230592330-0b64c0be-8c07-461b-b618-21298640812a.png">

**Desktop (please complete the following information):**
 - MacOS
 - Arc 
 - Chromium Engine Version 112.0.5615.49

**Comment by bvotteler** [comment]
@Chanakya888 , is this issue still present?
I was unable to reproduce it.

**Comment by Chanakya888** [comment]
I am unable to reproduce it now @bvotteler , we can close the issue :)

**Comment by bvotteler** [comment]
> I am unable to reproduce it now @bvotteler , we can close the issue :)

Awesome, thank you for reporting the issue and confirming that it isn't showing up anymore.
